// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bot.sql

package db

import (
	"context"
)

const createIfNotExists = `-- name: CreateIfNotExists :one
INSERT INTO bots (tgid, type)
VALUES ($1, $2)
ON CONFLICT (tgid, type) DO UPDATE
  SET tgid = EXCLUDED.tgid
RETURNING id, tgid, type, channel_id
`

type CreateIfNotExistsParams struct {
	Tgid int32
	Type string
}

func (q *Queries) CreateIfNotExists(ctx context.Context, arg CreateIfNotExistsParams) (Bot, error) {
	row := q.db.QueryRow(ctx, createIfNotExists, arg.Tgid, arg.Type)
	var i Bot
	err := row.Scan(
		&i.ID,
		&i.Tgid,
		&i.Type,
		&i.ChannelID,
	)
	return i, err
}
