// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: channel.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createChannel = `-- name: CreateChannel :one
INSERT INTO channels (code, channel_chat_id, admin_chat_id, discussions_chat_id)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateChannelParams struct {
	Code              string
	ChannelChatID     pgtype.Int8
	AdminChatID       pgtype.Int8
	DiscussionsChatID pgtype.Int8
}

func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) (int32, error) {
	row := q.db.QueryRow(ctx, createChannel,
		arg.Code,
		arg.ChannelChatID,
		arg.AdminChatID,
		arg.DiscussionsChatID,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const findChannelByCode = `-- name: FindChannelByCode :one
SELECT id, channel_chat_id, admin_chat_id, discussions_chat_id, decorations
FROM channels
WHERE code = $1
`

type FindChannelByCodeRow struct {
	ID                int32
	ChannelChatID     pgtype.Int8
	AdminChatID       pgtype.Int8
	DiscussionsChatID pgtype.Int8
	Decorations       pgtype.Text
}

func (q *Queries) FindChannelByCode(ctx context.Context, code string) (FindChannelByCodeRow, error) {
	row := q.db.QueryRow(ctx, findChannelByCode, code)
	var i FindChannelByCodeRow
	err := row.Scan(
		&i.ID,
		&i.ChannelChatID,
		&i.AdminChatID,
		&i.DiscussionsChatID,
		&i.Decorations,
	)
	return i, err
}

const findChannelById = `-- name: FindChannelById :one
SELECT code, channel_chat_id, admin_chat_id, discussions_chat_id, decorations
FROM channels
WHERE id = $1
`

type FindChannelByIdRow struct {
	Code              string
	ChannelChatID     pgtype.Int8
	AdminChatID       pgtype.Int8
	DiscussionsChatID pgtype.Int8
	Decorations       pgtype.Text
}

func (q *Queries) FindChannelById(ctx context.Context, id int32) (FindChannelByIdRow, error) {
	row := q.db.QueryRow(ctx, findChannelById, id)
	var i FindChannelByIdRow
	err := row.Scan(
		&i.Code,
		&i.ChannelChatID,
		&i.AdminChatID,
		&i.DiscussionsChatID,
		&i.Decorations,
	)
	return i, err
}

const updateChannel = `-- name: UpdateChannel :one
UPDATE channels
SET
  channel_chat_id = COALESCE($2, channel_chat_id),
  admin_chat_id = COALESCE($3, admin_chat_id),
  discussions_chat_id = COALESCE($4, discussions_chat_id),
  decorations = COALESCE($5, decorations)
WHERE id = $1
RETURNING id, code, channel_chat_id, admin_chat_id, discussions_chat_id, decorations
`

type UpdateChannelParams struct {
	ID                int32
	ChannelChatID     pgtype.Int8
	AdminChatID       pgtype.Int8
	DiscussionsChatID pgtype.Int8
	Decorations       pgtype.Text
}

func (q *Queries) UpdateChannel(ctx context.Context, arg UpdateChannelParams) (Channel, error) {
	row := q.db.QueryRow(ctx, updateChannel,
		arg.ID,
		arg.ChannelChatID,
		arg.AdminChatID,
		arg.DiscussionsChatID,
		arg.Decorations,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.ChannelChatID,
		&i.AdminChatID,
		&i.DiscussionsChatID,
		&i.Decorations,
	)
	return i, err
}
