// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: channel.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createChannel = `-- name: CreateChannel :one
WITH create_channel AS (
  INSERT INTO channels (code, channel_chat_id, admin_chat_id, discussions_chat_id)
  VALUES ($1, $2, $3, $4)
  RETURNING id, code, channel_chat_id, admin_chat_id, discussions_chat_id, decorations
)
UPDATE bots
SET channel_id = create_channel.id
FROM create_channel
WHERE tgid = $5 AND type = $6
RETURNING create_channel.id, create_channel.code, create_channel.channel_chat_id, create_channel.admin_chat_id, create_channel.discussions_chat_id, create_channel.decorations
`

type CreateChannelParams struct {
	Code              string
	ChannelChatID     pgtype.Int8
	AdminChatID       pgtype.Int8
	DiscussionsChatID pgtype.Int8
	Tgid              int64
	Type              string
}

type CreateChannelRow struct {
	ID                int32
	Code              string
	ChannelChatID     pgtype.Int8
	AdminChatID       pgtype.Int8
	DiscussionsChatID pgtype.Int8
	Decorations       pgtype.Text
}

func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) (CreateChannelRow, error) {
	row := q.db.QueryRow(ctx, createChannel,
		arg.Code,
		arg.ChannelChatID,
		arg.AdminChatID,
		arg.DiscussionsChatID,
		arg.Tgid,
		arg.Type,
	)
	var i CreateChannelRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.ChannelChatID,
		&i.AdminChatID,
		&i.DiscussionsChatID,
		&i.Decorations,
	)
	return i, err
}

const updateChannel = `-- name: UpdateChannel :one
UPDATE channels
SET
  channel_chat_id = COALESCE($2, channel_chat_id),
  admin_chat_id = COALESCE($3, admin_chat_id),
  discussions_chat_id = COALESCE($4, discussions_chat_id),
  decorations = COALESCE($5, decorations)
WHERE id = $1
RETURNING id, code, channel_chat_id, admin_chat_id, discussions_chat_id, decorations
`

type UpdateChannelParams struct {
	ID                int32
	ChannelChatID     pgtype.Int8
	AdminChatID       pgtype.Int8
	DiscussionsChatID pgtype.Int8
	Decorations       pgtype.Text
}

func (q *Queries) UpdateChannel(ctx context.Context, arg UpdateChannelParams) (Channel, error) {
	row := q.db.QueryRow(ctx, updateChannel,
		arg.ID,
		arg.ChannelChatID,
		arg.AdminChatID,
		arg.DiscussionsChatID,
		arg.Decorations,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.ChannelChatID,
		&i.AdminChatID,
		&i.DiscussionsChatID,
		&i.Decorations,
	)
	return i, err
}
