// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Bot struct {
	ID        int32
	Tgid      int64
	Type      string
	ChannelID pgtype.Int4
}

type Channel struct {
	ID                int32
	Code              string
	ChannelChatID     pgtype.Int8
	AdminChatID       pgtype.Int8
	DiscussionsChatID pgtype.Int8
	Decorations       pgtype.Text
}

type Take struct {
	ID             int32
	Status         string
	UserMessageID  int64
	AdminMessageID int64
	UserChannelID  int32
	ChannelID      int32
}

type User struct {
	ID   int32
	Tgid int64
}

type UserChannel struct {
	ID        int32
	UserID    int32
	ChannelID int32
	Role      string
	Anonimity pgtype.Bool
}
