// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Bot struct {
	ID        int32
	Tgid      int32
	Type      string
	ChannelID pgtype.Int4
}

type Channel struct {
	ID                int32
	Code              string
	ChannelChatID     pgtype.Int4
	AdminChatID       pgtype.Int4
	DiscussionsChatID pgtype.Int4
	Decorations       pgtype.Text
}
