// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: replies.sql

package db

import (
	"context"
)

const createReply = `-- name: CreateReply :one
INSERT INTO replies (user_message_id, admin_message_id, take_id, channel_id)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateReplyParams struct {
	UserMessageID  int64
	AdminMessageID int64
	TakeID         int32
	ChannelID      int32
}

func (q *Queries) CreateReply(ctx context.Context, arg CreateReplyParams) (int32, error) {
	row := q.db.QueryRow(ctx, createReply,
		arg.UserMessageID,
		arg.AdminMessageID,
		arg.TakeID,
		arg.ChannelID,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getReplyByMsgIdAndChannelId = `-- name: GetReplyByMsgIdAndChannelId :one
SELECT id, user_message_id, admin_message_id, take_id, channel_id
FROM replies
WHERE (user_message_id = $1 OR admin_message_id = $1) AND channel_id = $2
`

type GetReplyByMsgIdAndChannelIdParams struct {
	UserMessageID int64
	ChannelID     int32
}

func (q *Queries) GetReplyByMsgIdAndChannelId(ctx context.Context, arg GetReplyByMsgIdAndChannelIdParams) (Reply, error) {
	row := q.db.QueryRow(ctx, getReplyByMsgIdAndChannelId, arg.UserMessageID, arg.ChannelID)
	var i Reply
	err := row.Scan(
		&i.ID,
		&i.UserMessageID,
		&i.AdminMessageID,
		&i.TakeID,
		&i.ChannelID,
	)
	return i, err
}

const getReplyByMsgIdAndTakeId = `-- name: GetReplyByMsgIdAndTakeId :one
SELECT id, user_message_id, admin_message_id, take_id, channel_id
FROM replies
WHERE (user_message_id = $1 OR admin_message_id = $1) AND take_id = $2
`

type GetReplyByMsgIdAndTakeIdParams struct {
	UserMessageID int64
	TakeID        int32
}

func (q *Queries) GetReplyByMsgIdAndTakeId(ctx context.Context, arg GetReplyByMsgIdAndTakeIdParams) (Reply, error) {
	row := q.db.QueryRow(ctx, getReplyByMsgIdAndTakeId, arg.UserMessageID, arg.TakeID)
	var i Reply
	err := row.Scan(
		&i.ID,
		&i.UserMessageID,
		&i.AdminMessageID,
		&i.TakeID,
		&i.ChannelID,
	)
	return i, err
}
