// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: takes.sql

package db

import (
	"context"
)

const createTake = `-- name: CreateTake :one
INSERT INTO takes (user_message_id, admin_message_id, user_channel_id, channel_id)
VALUES ($1, $2, $3, $4)
RETURNING id, user_message_id, admin_message_id, user_channel_id, channel_id
`

type CreateTakeParams struct {
	UserMessageID  int64
	AdminMessageID int64
	UserChannelID  int32
	ChannelID      int32
}

type CreateTakeRow struct {
	ID             int32
	UserMessageID  int64
	AdminMessageID int64
	UserChannelID  int32
	ChannelID      int32
}

func (q *Queries) CreateTake(ctx context.Context, arg CreateTakeParams) (CreateTakeRow, error) {
	row := q.db.QueryRow(ctx, createTake,
		arg.UserMessageID,
		arg.AdminMessageID,
		arg.UserChannelID,
		arg.ChannelID,
	)
	var i CreateTakeRow
	err := row.Scan(
		&i.ID,
		&i.UserMessageID,
		&i.AdminMessageID,
		&i.UserChannelID,
		&i.ChannelID,
	)
	return i, err
}

const getTakeById = `-- name: GetTakeById :one
SELECT id, status, user_message_id, admin_message_id, user_channel_id, channel_id
FROM takes
WHERE id = $1 AND channel_id = $2
`

type GetTakeByIdParams struct {
	ID        int32
	ChannelID int32
}

type GetTakeByIdRow struct {
	ID             int32
	Status         string
	UserMessageID  int64
	AdminMessageID int64
	UserChannelID  int32
	ChannelID      int32
}

func (q *Queries) GetTakeById(ctx context.Context, arg GetTakeByIdParams) (GetTakeByIdRow, error) {
	row := q.db.QueryRow(ctx, getTakeById, arg.ID, arg.ChannelID)
	var i GetTakeByIdRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.UserMessageID,
		&i.AdminMessageID,
		&i.UserChannelID,
		&i.ChannelID,
	)
	return i, err
}

const getTakeByMsgId = `-- name: GetTakeByMsgId :one
SELECT id, status, user_message_id, admin_message_id, user_channel_id, channel_id
FROM takes
WHERE user_message_id = $1 OR admin_message_id = $1 AND channel_id = $2
`

type GetTakeByMsgIdParams struct {
	UserMessageID int64
	ChannelID     int32
}

type GetTakeByMsgIdRow struct {
	ID             int32
	Status         string
	UserMessageID  int64
	AdminMessageID int64
	UserChannelID  int32
	ChannelID      int32
}

func (q *Queries) GetTakeByMsgId(ctx context.Context, arg GetTakeByMsgIdParams) (GetTakeByMsgIdRow, error) {
	row := q.db.QueryRow(ctx, getTakeByMsgId, arg.UserMessageID, arg.ChannelID)
	var i GetTakeByMsgIdRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.UserMessageID,
		&i.AdminMessageID,
		&i.UserChannelID,
		&i.ChannelID,
	)
	return i, err
}
