// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserAnonimity = `-- name: GetUserAnonimity :one
SELECT anonimity
FROM user_channels
WHERE user_id = $1 AND channel_id = $2
`

type GetUserAnonimityParams struct {
	UserID    int32
	ChannelID int32
}

func (q *Queries) GetUserAnonimity(ctx context.Context, arg GetUserAnonimityParams) (pgtype.Bool, error) {
	row := q.db.QueryRow(ctx, getUserAnonimity, arg.UserID, arg.ChannelID)
	var anonimity pgtype.Bool
	err := row.Scan(&anonimity)
	return anonimity, err
}

const getUserChannelById = `-- name: GetUserChannelById :one
SELECT id, user_id, channel_id, role, anonimity
FROM user_channels
WHERE id = $1
`

func (q *Queries) GetUserChannelById(ctx context.Context, id int32) (UserChannel, error) {
	row := q.db.QueryRow(ctx, getUserChannelById, id)
	var i UserChannel
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ChannelID,
		&i.Role,
		&i.Anonimity,
	)
	return i, err
}

const getUserChannelId = `-- name: GetUserChannelId :one
SELECT id
FROM user_channels
WHERE user_id = $1 AND channel_id = $2
`

type GetUserChannelIdParams struct {
	UserID    int32
	ChannelID int32
}

func (q *Queries) GetUserChannelId(ctx context.Context, arg GetUserChannelIdParams) (int32, error) {
	row := q.db.QueryRow(ctx, getUserChannelId, arg.UserID, arg.ChannelID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getUserIdByTgId = `-- name: GetUserIdByTgId :one
SELECT id
FROM users
WHERE tgid = $1
`

func (q *Queries) GetUserIdByTgId(ctx context.Context, tgid int64) (int32, error) {
	row := q.db.QueryRow(ctx, getUserIdByTgId, tgid)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getUserRole = `-- name: GetUserRole :one
SELECT role
FROM user_channels
WHERE user_id = $1 AND channel_id = $2
`

type GetUserRoleParams struct {
	UserID    int32
	ChannelID int32
}

func (q *Queries) GetUserRole(ctx context.Context, arg GetUserRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, getUserRole, arg.UserID, arg.ChannelID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const getUserTgIdById = `-- name: GetUserTgIdById :one
SELECT tgid
FROM users
WHERE id = $1
`

func (q *Queries) GetUserTgIdById(ctx context.Context, id int32) (int64, error) {
	row := q.db.QueryRow(ctx, getUserTgIdById, id)
	var tgid int64
	err := row.Scan(&tgid)
	return tgid, err
}

const toggleUserAnonimity = `-- name: ToggleUserAnonimity :one
UPDATE user_channels
SET anonimity = NOT anonimity
WHERE user_id = $1 AND channel_id = $2
RETURNING anonimity
`

type ToggleUserAnonimityParams struct {
	UserID    int32
	ChannelID int32
}

func (q *Queries) ToggleUserAnonimity(ctx context.Context, arg ToggleUserAnonimityParams) (pgtype.Bool, error) {
	row := q.db.QueryRow(ctx, toggleUserAnonimity, arg.UserID, arg.ChannelID)
	var anonimity pgtype.Bool
	err := row.Scan(&anonimity)
	return anonimity, err
}

const updateUserRole = `-- name: UpdateUserRole :exec
UPDATE user_channels
SET role = $1
WHERE user_id = $2 AND channel_id = $3
`

type UpdateUserRoleParams struct {
	Role      string
	UserID    int32
	ChannelID int32
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error {
	_, err := q.db.Exec(ctx, updateUserRole, arg.Role, arg.UserID, arg.ChannelID)
	return err
}

const upsertUser = `-- name: UpsertUser :one
WITH upsert_user AS (
  INSERT INTO users (tgid)
  VALUES ($1)
  ON CONFLICT (tgid) DO UPDATE
  SET tgid = EXCLUDED.tgid
  RETURNING id
),
upsert_user_channel AS (
  INSERT INTO user_channels (user_id, channel_id)
  SELECT id, $2 FROM upsert_user
  ON CONFLICT (user_id, channel_id) DO UPDATE
  SET role = EXCLUDED.role
)
SELECT id FROM upsert_user
`

type UpsertUserParams struct {
	Tgid      int64
	ChannelID int32
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (int32, error) {
	row := q.db.QueryRow(ctx, upsertUser, arg.Tgid, arg.ChannelID)
	var id int32
	err := row.Scan(&id)
	return id, err
}
